# Generated by Django 3.2.9 on 2021-12-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_auto_20211210_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('speed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('sample_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('graphic_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.graphiccard')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('speed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('speed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_address', models.TextField()),
                ('transaction_time', models.DateTimeField()),
                ('delivery_fees', models.FloatField()),
                ('final_price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.user')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.monitor'),
        ),
        migrations.AddField(
            model_name='item',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.processor'),
        ),
    ]
