# Generated by Django 3.2.9 on 2021-12-22 11:39

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'kind',
            },
        ),
        migrations.CreateModel(
            name='GoodsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('g_name', models.CharField(max_length=50)),
                ('g_img', models.ImageField(blank=True, null=True, upload_to=store.models.upload_image_path)),
                ('g_price', models.DecimalField(decimal_places=4, default=1000, max_digits=20)),
                ('g_repertory', models.IntegerField(default=0)),
                ('g_created_at', models.DateTimeField(auto_now_add=True)),
                ('g_description', models.TextField()),
                ('isDelete', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('gtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.articlecategory')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
            },
        ),
    ]
