# Generated by Django 3.2.9 on 2021-12-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': '种类', 'verbose_name_plural': '种类'},
        ),
    ]
