# Generated by Django 3.2.9 on 2021-12-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_articlecategory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsvalue',
            old_name='g_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='goodsvalue',
            old_name='g_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='goodsvalue',
            old_name='g_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='goodsvalue',
            old_name='g_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='goodsvalue',
            old_name='g_repertory',
            new_name='repertory',
        ),
        migrations.RenameField(
            model_name='goodsvalue',
            old_name='g_name',
            new_name='title',
        ),
    ]
