# Generated by Django 3.2.9 on 2021-12-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
